name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run E2E tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: privyloop_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup test database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
        run: |
          pnpm run db:migrate
          pnpm run db:seed:test

      - name: Build application
        run: pnpm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_URL: http://localhost:3030
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Start application in background
        run: |
          pnpm run start &
          sleep 10
        env:
          NODE_ENV: production
          PORT: 3030
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_APP_URL: http://localhost:3030

      - name: Wait for application to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3030; do sleep 2; done'

      - name: Run E2E tests
        run: pnpm exec playwright test
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3030
          CI: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-screenshots
          path: tests/e2e/screenshots/
          retention-days: 7

  e2e-tests-multiple-browsers:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'full-e2e')
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: privyloop_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup test database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
        run: |
          pnpm run db:migrate
          pnpm run db:seed:test

      - name: Build application
        run: pnpm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_URL: http://localhost:3030
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
          BETTER_AUTH_SECRET: test-secret-key-for-ci

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps ${{ matrix.browser }}

      - name: Start application in background
        run: |
          pnpm run start &
          sleep 10
        env:
          NODE_ENV: production
          PORT: 3030
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_APP_URL: http://localhost:3030

      - name: Wait for application to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3030; do sleep 2; done'

      - name: Run E2E tests on ${{ matrix.browser }}
        run: pnpm exec playwright test --project=${{ matrix.browser }}
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3030
          CI: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30

  visual-regression-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: privyloop_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup test database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
        run: |
          pnpm run db:migrate
          pnpm run db:seed:test

      - name: Build application
        run: pnpm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_URL: http://localhost:3030
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
          BETTER_AUTH_SECRET: test-secret-key-for-ci

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Start application in background
        run: |
          pnpm run start &
          sleep 10
        env:
          NODE_ENV: production
          PORT: 3030
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/privyloop_test
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_APP_URL: http://localhost:3030

      - name: Wait for application to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3030; do sleep 2; done'

      - name: Run visual regression tests
        run: pnpm exec playwright test --grep="visual" --project=chromium
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3030
          CI: true

      - name: Upload visual diff artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-regression-diffs
          path: test-results/
          retention-days: 7